VEXT_TARGET_PROJECT := Z10
VEXT_BASE_PROJECT := Z10
ifndef VEXT_TARGET_PROJECT_FOLDER
VEXT_TARGET_PROJECT_FOLDER := $(LOCAL_PATH)
endif
VEXT_PROJECT_FOLDER := $(VEXT_TARGET_PROJECT_FOLDER)

VEXT_PROJECT_CONFIG_MK := $(VEXT_TARGET_PROJECT_FOLDER)/ProjectConfig.mk
include $(VEXT_PROJECT_CONFIG_MK)
include $(wildcard $(VEXT_TARGET_PROJECT_FOLDER)/RuntimeSwitchConfig.mk)
$(call inherit-product, $(VEXT_TARGET_PROJECT_FOLDER)/device.mk)
ifndef HAL_TARGET_PROJECT
$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)
endif
ifneq ($(wildcard $(VEXT_TARGET_PROJECT_FOLDER)/vnd_$(VEXT_TARGET_PROJECT).mk),)
mgk_name := $(strip $(shell cat $(VEXT_TARGET_PROJECT_FOLDER)/vnd_$(VEXT_TARGET_PROJECT).mk | grep 'KRN_TARGET_PROJECT\s*:=' | sed -e 's/KRN_TARGET_PROJECT\s*:=\s*//'))
PRODUCT_PROPERTY_OVERRIDES += ro.vendor.mgk_name=$(mgk_name)
endif

ifndef SYS_TARGET_PROJECT
PRODUCT_BUILD_SYSTEM_IMAGE := false
PRODUCT_BUILD_PRODUCT_IMAGE := false
endif
PRODUCT_BUILD_VENDOR_IMAGE :=

PRODUCT_MANUFACTURER := ALONG
PRODUCT_NAME := vext_Z10
PRODUCT_DEVICE := Z10
PRODUCT_MODEL := MP01
PRODUCT_POLICY := android.policy_phone
PRODUCT_BRAND := Minimal_Phone

ifndef KRN_TARGET_PROJECT
KERNEL_DEFCONFIG ?= gki_defconfig
endif
PRELOADER_TARGET_PRODUCT ?= Z10
LK_PROJECT ?= Z10
TINYSYS_TARGET_PROJECT := Z10
TINYSYS_TARGET_PROJECT_FOLDER := $(VEXT_TARGET_PROJECT_FOLDER)
TRUSTZONE_TARGET_PROJECT := Z10
