KRN_TARGET_PROJECT := mgk_64_entry_level_k510
KRN_TARGET_PROJECT_FOLDER := device/mediatek/kernel/$(KRN_TARGET_PROJECT)
HAL_TARGET_PROJECT := mgvi_64_armv82
HAL_TARGET_PROJECT_FOLDER := device/mediatek/vendor/$(HAL_TARGET_PROJECT)
VEXT_TARGET_PROJECT := Z10
VEXT_TARGET_PROJECT_FOLDER := device/mediatekprojects/$(VEXT_TARGET_PROJECT)

include $(KRN_TARGET_PROJECT_FOLDER)/krn_$(KRN_TARGET_PROJECT).mk
include $(HAL_TARGET_PROJECT_FOLDER)/hal_$(HAL_TARGET_PROJECT).mk
include $(VEXT_TARGET_PROJECT_FOLDER)/vext_$(VEXT_TARGET_PROJECT).mk

PRODUCT_NAME := vnd_Z10
