include device/mediatek/vendor/common/BoardConfig-kernel.mk

ifndef VEXT_TARGET_PROJECT
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT :=
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 41943040
#BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true
BOARD_USES_FULL_RECOVERY_IMAGE := true
endif
