BUILD_KERNEL = yes
LINUX_KERNEL_VERSION = kernel-5.10
MTK_BT_SUPPORT = yes
MTK_COMBO_SUPPORT = yes
MTK_FM_SUPPORT = yes
MTK_GPS_SUPPORT = yes
MTK_K64_SUPPORT = yes
MTK_WLAN_SUPPORT = yes
MTK_TEST_AIT = yes
MTK_TEST_COV_LINE = no
MTK_TEST_IT = yes
MTK_TEST_ST = yes
MTK_TEST_UT = yes

