/****************************************************************************
 ****************************************************************************
 ***
 ***   This header was automatically generated from a Linux kernel header
 ***   of the same name, to make information necessary for userspace to
 ***   call into the kernel available to libc.  It contains only constants,
 ***   structures, and macros generated from the original header, and thus,
 ***   contains no copyrightable information.
 ***
 ***   To edit the content of this header, modify the corresponding
 ***   source file (e.g. under external/kernel-headers/original/) then
 ***   run bionic/libc/kernel/tools/update_all.py
 ***
 ***   Any manual change here will be lost the next time this script will
 ***   be run. You've been warned!
 ***
 ****************************************************************************
 ****************************************************************************/
#ifndef __CMDQ_ENGINE_H__
#define __CMDQ_ENGINE_H__
typedef enum CMDQ_ENG_ENUM {
  CMDQ_ENG_WPEI = 0,
  CMDQ_ENG_WPEO,
  CMDQ_ENG_WPEI2,
  CMDQ_ENG_WPEO2,
  CMDQ_ENG_ISP_IMGI,
  CMDQ_ENG_ISP_IMGI2,
  CMDQ_ENG_ISP_IMG2O,
  CMDQ_ENG_ISP_IMG2O2,
  CMDQ_ENG_MDP_CAMIN,
  CMDQ_ENG_MDP_CAMIN2,
  CMDQ_ENG_MDP_CAMIN3,
  CMDQ_ENG_MDP_CAMIN4,
  CMDQ_ENG_MDP_RDMA0,
  CMDQ_ENG_MDP_RDMA1,
  CMDQ_ENG_MDP_RDMA2,
  CMDQ_ENG_MDP_RDMA3,
  CMDQ_ENG_MDP_FG0,
  CMDQ_ENG_MDP_FG1,
  CMDQ_ENG_MDP_PQ0_SOUT,
  CMDQ_ENG_MDP_PQ1_SOUT,
  CMDQ_ENG_MDP_HDR0,
  CMDQ_ENG_MDP_HDR1,
  CMDQ_ENG_MDP_COLOR0,
  CMDQ_ENG_MDP_COLOR1,
  CMDQ_ENG_MDP_AAL0,
  CMDQ_ENG_MDP_AAL1,
  CMDQ_ENG_MDP_AAL2,
  CMDQ_ENG_MDP_AAL3,
  CMDQ_ENG_MDP_RSZ0,
  CMDQ_ENG_MDP_RSZ1,
  CMDQ_ENG_MDP_RSZ2,
  CMDQ_ENG_MDP_RSZ3,
  CMDQ_ENG_MDP_TDSHP0,
  CMDQ_ENG_MDP_TDSHP1,
  CMDQ_ENG_MDP_TDSHP2,
  CMDQ_ENG_MDP_TDSHP3,
  CMDQ_ENG_MDP_TCC0,
  CMDQ_ENG_MDP_TCC1,
  CMDQ_ENG_MDP_TCC2,
  CMDQ_ENG_MDP_TCC3,
  CMDQ_ENG_MDP_WROT0,
  CMDQ_ENG_MDP_WROT1,
  CMDQ_ENG_MDP_WROT2,
  CMDQ_ENG_MDP_WROT3,
  CMDQ_ENG_DPE,
  CMDQ_ENG_RSC,
  CMDQ_ENG_GEPF,
  CMDQ_ENG_EAF,
  CMDQ_ENG_OWE,
  CMDQ_ENG_MFB,
  CMDQ_ENG_FDVT,
  CMDQ_ENG_ISP_VIPI,
  CMDQ_ENG_ISP_LCEI,
  CMDQ_ENG_ISP_IMG3O,
  CMDQ_ENG_ISP_SMXIO,
  CMDQ_ENG_ISP_DMGI_DEPI,
  CMDQ_ENG_ISP_IMGCI,
  CMDQ_ENG_ISP_UFBCI,
  CMDQ_ENG_ISP_UFBCO,
  CMDQ_ENG_ISP_MSS,
  CMDQ_ENG_ISP_MSF,
  CMDQ_ENG_INORDER,
  CMDQ_ENG_ISP_TIMGO = 63,
  CMDQ_ENG_MDP_WDMA = 63,
  CMDQ_MAX_ENGINE_COUNT
} CMDQ_ENG_ENUM;
enum MDP_ENG_BASE {
  ENGBASE_MMSYS_CONFIG,
  ENGBASE_MDP_RDMA0,
  ENGBASE_MDP_RDMA1,
  ENGBASE_MDP_RDMA2,
  ENGBASE_MDP_RDMA3,
  ENGBASE_MDP_FG0,
  ENGBASE_MDP_FG1,
  ENGBASE_MDP_AAL0,
  ENGBASE_MDP_AAL1,
  ENGBASE_MDP_AAL2,
  ENGBASE_MDP_AAL3,
  ENGBASE_MDP_HDR0,
  ENGBASE_MDP_HDR1,
  ENGBASE_MDP_RSZ0,
  ENGBASE_MDP_RSZ1,
  ENGBASE_MDP_RSZ2,
  ENGBASE_MDP_RSZ3,
  ENGBASE_MDP_WROT0,
  ENGBASE_MDP_WROT1,
  ENGBASE_MDP_WROT2,
  ENGBASE_MDP_WROT3,
  ENGBASE_MDP_TDSHP0,
  ENGBASE_MDP_TDSHP1,
  ENGBASE_MDP_TDSHP2,
  ENGBASE_MDP_TDSHP3,
  ENGBASE_MDP_TCC0,
  ENGBASE_MDP_TCC1,
  ENGBASE_MDP_TCC2,
  ENGBASE_MDP_TCC3,
  ENGBASE_MDP_COLOR0,
  ENGBASE_MDP_COLOR1,
  ENGBASE_MMSYS_MUTEX,
  ENGBASE_ISP_MSFDL,
  ENGBASE_ISP_MSS,
  ENGBASE_ISP_MFB,
  ENGBASE_ISP_DIP_A0,
  ENGBASE_ISP_DIP_A1,
  ENGBASE_ISP_DIP_A7,
  ENGBASE_IMGSYS2_CONFIG,
  ENGBASE_ISP_DIP_B0,
  ENGBASE_ISP_DIP_B1,
  ENGBASE_ISP_DIP_B7,
  ENGBASE_ISP_WPE_A,
  ENGBASE_ISP_WPE_B,
  ENGBASE_COUNT
};
#endif
