/****************************************************************************
 ****************************************************************************
 ***
 ***   This header was automatically generated from a Linux kernel header
 ***   of the same name, to make information necessary for userspace to
 ***   call into the kernel available to libc.  It contains only constants,
 ***   structures, and macros generated from the original header, and thus,
 ***   contains no copyrightable information.
 ***
 ***   To edit the content of this header, modify the corresponding
 ***   source file (e.g. under external/kernel-headers/original/) then
 ***   run bionic/libc/kernel/tools/update_all.py
 ***
 ***   Any manual change here will be lost the next time this script will
 ***   be run. You've been warned!
 ***
 ****************************************************************************
 ****************************************************************************/
#ifndef __MTK_CONTROLS_H
#define __MTK_CONTROLS_H

#include <linux/videodev2.h>
#include <linux/v4l2-controls.h>

/* Mediatek control IDs */
#define V4L2_CID_MPEG_MTK_BASE \
	(V4L2_CTRL_CLASS_MPEG | 0x2000)
#define V4L2_CID_MPEG_MTK_FRAME_INTERVAL \
	(V4L2_CID_MPEG_MTK_BASE+0)
#define V4L2_CID_MPEG_MTK_ERRORMB_MAP \
	(V4L2_CID_MPEG_MTK_BASE+1)
#define V4L2_CID_MPEG_MTK_DECODE_MODE \
	(V4L2_CID_MPEG_MTK_BASE+2)
#define V4L2_CID_MPEG_MTK_FRAME_SIZE \
	(V4L2_CID_MPEG_MTK_BASE+3)
#define V4L2_CID_MPEG_MTK_FIXED_MAX_FRAME_BUFFER \
	(V4L2_CID_MPEG_MTK_BASE+4)
#define V4L2_CID_MPEG_MTK_CRC_PATH \
	(V4L2_CID_MPEG_MTK_BASE+5)
#define V4L2_CID_MPEG_MTK_GOLDEN_PATH \
	(V4L2_CID_MPEG_MTK_BASE+6)
#define V4L2_CID_MPEG_MTK_COLOR_DESC \
	(V4L2_CID_MPEG_MTK_BASE+7)
#define V4L2_CID_MPEG_MTK_ASPECT_RATIO \
	(V4L2_CID_MPEG_MTK_BASE+8)
#define V4L2_CID_MPEG_MTK_SET_WAIT_KEY_FRAME \
	(V4L2_CID_MPEG_MTK_BASE+9)
#define V4L2_CID_MPEG_MTK_SET_NAL_SIZE_LENGTH \
	(V4L2_CID_MPEG_MTK_BASE+10)
#define V4L2_CID_MPEG_MTK_SEC_DECODE \
	(V4L2_CID_MPEG_MTK_BASE+11)
#define V4L2_CID_MPEG_MTK_FIX_BUFFERS \
	(V4L2_CID_MPEG_MTK_BASE+12)
#define V4L2_CID_MPEG_MTK_FIX_BUFFERS_SVP \
	(V4L2_CID_MPEG_MTK_BASE+13)
#define V4L2_CID_MPEG_MTK_INTERLACING \
	(V4L2_CID_MPEG_MTK_BASE+14)
#define V4L2_CID_MPEG_MTK_CODEC_TYPE \
	(V4L2_CID_MPEG_MTK_BASE+15)
#define V4L2_CID_MPEG_MTK_OPERATING_RATE \
	(V4L2_CID_MPEG_MTK_BASE+16)
#define V4L2_CID_MPEG_MTK_SEC_ENCODE \
	(V4L2_CID_MPEG_MTK_BASE+17)
#define V4L2_CID_MPEG_MTK_QUEUED_FRAMEBUF_COUNT \
	(V4L2_CID_MPEG_MTK_BASE+18)
#define V4L2_CID_MPEG_MTK_UFO_MODE \
	(V4L2_CID_MPEG_MTK_BASE+19)
#define V4L2_CID_MPEG_MTK_ENCODE_SCENARIO \
	(V4L2_CID_MPEG_MTK_BASE+20)
#define V4L2_CID_MPEG_MTK_ENCODE_NONREFP \
	(V4L2_CID_MPEG_MTK_BASE+21)
#define V4L2_CID_MPEG_MTK_ENCODE_DETECTED_FRAMERATE \
	(V4L2_CID_MPEG_MTK_BASE+22)
#define V4L2_CID_MPEG_MTK_ENCODE_RFS_ON \
	(V4L2_CID_MPEG_MTK_BASE+23)
#define V4L2_CID_MPEG_MTK_ENCODE_OPERATION_RATE \
	(V4L2_CID_MPEG_MTK_BASE+24)
#define V4L2_CID_MPEG_MTK_ENCODE_ROI_RC_QP \
	(V4L2_CID_MPEG_MTK_BASE+25)
#define V4L2_CID_MPEG_MTK_ENCODE_ROI_ON \
	(V4L2_CID_MPEG_MTK_BASE+26)
#define V4L2_CID_MPEG_MTK_ENCODE_GRID_SIZE \
	(V4L2_CID_MPEG_MTK_BASE+27)
#define V4L2_CID_MPEG_MTK_RESOLUTION_CHANGE \
	(V4L2_CID_MPEG_MTK_BASE+28)
#define V4L2_CID_MPEG_MTK_MAX_WIDTH \
	(V4L2_CID_MPEG_MTK_BASE+29)
#define V4L2_CID_MPEG_MTK_MAX_HEIGHT \
	(V4L2_CID_MPEG_MTK_BASE+30)
#define V4L2_CID_MPEG_MTK_ENCODE_RC_I_FRAME_QP \
	(V4L2_CID_MPEG_MTK_BASE+31)
#define V4L2_CID_MPEG_MTK_ENCODE_RC_P_FRAME_QP \
	(V4L2_CID_MPEG_MTK_BASE+32)
#define V4L2_CID_MPEG_MTK_ENCODE_RC_B_FRAME_QP \
	(V4L2_CID_MPEG_MTK_BASE+33)

#define V4L2_CID_MPEG_VIDEO_ENABLE_TSVC \
	(V4L2_CID_MPEG_MTK_BASE+34)
#define V4L2_CID_MPEG_MTK_ENCODE_NONREFP_FREQ \
	(V4L2_CID_MPEG_MTK_BASE+35)

#define V4L2_CID_MPEG_MTK_ENCODE_RC_MAX_QP \
	(V4L2_CID_MPEG_MTK_BASE+36)
#define V4L2_CID_MPEG_MTK_ENCODE_RC_MIN_QP \
	(V4L2_CID_MPEG_MTK_BASE+37)
#define V4L2_CID_MPEG_MTK_ENCODE_RC_I_P_QP_DELTA \
	(V4L2_CID_MPEG_MTK_BASE+38)
#define V4L2_CID_MPEG_MTK_ENCODE_RC_QP_CONTROL_MODE \
	(V4L2_CID_MPEG_MTK_BASE+39)
enum v4l2_mpeg_video_qp_control_mode {
	V4L2_MPEG_VIDEO_QP_CONTROL_MODE_DEF		= 0,
	V4L2_MPEG_VIDEO_QP_CONTROL_MODE_FRAME	= 1,
	V4L2_MPEG_VIDEO_QP_CONTROL_MODE_MB		= 2,
};
#define V4L2_CID_MPEG_MTK_ENCODE_RC_FRAME_LEVEL_QP \
	(V4L2_CID_MPEG_MTK_BASE+40)

#define V4L2_CID_MPEG_MTK_ENCODE_MAX_REFP_NUM \
	(V4L2_CID_MPEG_MTK_BASE+41)

#define V4L2_CID_MPEG_MTK_ENCODE_REFP_DISTANCE \
	(V4L2_CID_MPEG_MTK_BASE+42)

#define V4L2_CID_MPEG_MTK_ENCODE_REFP_MAX_FRAME_NUM \
	(V4L2_CID_MPEG_MTK_BASE+43)

#define V4L2_CID_MPEG_MTK_ENCODE_REFP_FRAME_NUM \
	(V4L2_CID_MPEG_MTK_BASE+44)

#define V4L2_CID_MPEG_MTK_ENCODE_ENABLE_HIGHQUALITY \
	(V4L2_CID_MPEG_MTK_BASE+45)

#define V4L2_CID_MPEG_MTK_LOG \
	(V4L2_CID_MPEG_MTK_BASE+46)

#define V4L2_CID_MPEG_VIDEO_ENABLE_DUMMY_NAL \
	(V4L2_CID_MPEG_MTK_BASE+47)

#define V4L2_CID_MPEG_MTK_REAL_TIME_PRIORITY \
	(V4L2_CID_MPEG_MTK_BASE+48)

#define V4L2_CID_MPEG_MTK_VCP_PROP \
	(V4L2_CID_MPEG_MTK_BASE+49)

#define V4L2_CID_MPEG_MTK_GET_LOG \
	(V4L2_CID_MPEG_MTK_BASE+63)

#define V4L2_CID_MPEG_MTK_GET_VCP_PROP \
	(V4L2_CID_MPEG_MTK_BASE+64)

#define V4L2_CID_MPEG_VIDEO_H264_SPS (V4L2_CID_MPEG_BASE + 383)
#define V4L2_CID_MPEG_VIDEO_H264_PPS (V4L2_CID_MPEG_BASE + 384)
#define V4L2_CID_MPEG_VIDEO_H264_SCALING_MATRIX (V4L2_CID_MPEG_BASE + 385)
#define V4L2_CID_MPEG_VIDEO_H264_SLICE_PARAM (V4L2_CID_MPEG_BASE + 386)
#define V4L2_CID_MPEG_VIDEO_H264_DECODE_PARAM (V4L2_CID_MPEG_BASE + 387)
#define V4L2_CID_MPEG_VIDEO_VP8_FRAME_HDR (V4L2_CID_MPEG_BASE + 512)

#ifndef V4L2_CID_MPEG_VIDEO_VP9_LEVEL
enum {
	V4L2_MPEG_VIDEO_BITRATE_MODE_CQ = V4L2_MPEG_VIDEO_BITRATE_MODE_CBR + 1,
};

enum {
	V4L2_MPEG_VIDEO_H264_LEVEL_5_2 = V4L2_MPEG_VIDEO_H264_LEVEL_5_1 + 1,
};
#endif

enum {
        V4L2_MPEG_VIDEO_MPEG4_LEVEL_6 = V4L2_MPEG_VIDEO_MPEG4_LEVEL_5 + 1,
};

#endif
